### ISSUE TITLE
Rename makina.recipe.postgres to makina.buildout.recipe.postgres

### ISSUE THREAD

**Issue by AntoineCezar** [makinacorpus/makina.recipe.postgres#1]
Assuming all recipes are buildout recipes is not fair nor futur proof.

**Comment by kiorky** [comment]
-1000
makina.recipe is a good namespace for that pupose.
Besides, 4th nested namespaces are ugly and discouraged.

**Comment by AntoineCezar** [comment]
> -1000

not an argument

> makina.recipe is a good namespace for that pupose.

Only if buildout is the only tool that use the word "recipe" and even so its not future proof. What if we start to use puppet or saltstack ?

> Besides, 4th nested namespaces are ugly and discouraged.

Maybe "buildout.recipe.postgres" then ?

**Comment by toutpt** [comment]
IMO renaming is useless but if you feel concerned and want to achieve this you can go ahead
